### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by xiaoguanyu** [qwurey/flume-source-taildir-recursive#1]
你好，我在编译的过程中一直报错，报错信息如下：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project flume-taildir-source: Compilation failu
re: Compilation failure:
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[40,30] 错误: 找不到符号
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[171,44] 错误: 找不到符号
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[172,14] 错误: 找不到符号
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[173,46] 错误: 找不到符号
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[174,14] 错误: 找不到符号
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[238,2] 错误: 方法不会覆盖或实现超类型的方法
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Taildi
rSource.java:[243,2] 错误: 方法不会覆盖或实现超类型的方法
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Reliab
leTaildirEventReader.java:[141,29] 错误: -source 1.6 中不支持 switch 中存在字符
串
[ERROR] \flume-taildir-source\src\main\java\com\urey\flume\source\taildir\Reliab
leTaildirEventReader.java:[440,42] 错误: 不可转换的类型
[ERROR] -> [Help 1]
[ERROR]

**Comment by qwurey** [comment]
你好，谢谢你的反馈。

这里是因为该source依赖1.7.0的某些模块，比如依赖**flume-ng-core**，而**该模块与1.6.0的flume-ng-core有变动，所以如果在1.6.0中加入该source还需要按照编译提示的错误一个一个进行更改，直到编译通过，使1.7.0的taildir source可以适配在1.6.0上**。

这一部分的修改不在该source的代码中，而是在相应的模块中，比如会在flume-ng-core中的某些class中，需要使用jdk1.7+的版本等等。因为改动的部分非常零散且简单，所以我没有上传上来，之后我会在readme中加入说明。
